#!/usr/bin/env -S -- bash
# -*- coding: ascii -*-

set -e -o pipefail
cd "$(readlink -e -- "${0%/*}/.." || true)"

###############################################################################################################################################################

dependency_exists() {
    if ! type "${1}" &> /dev/null; then
        echo "Missing dependency: '${1}'" >&2
        return 1
    fi
    return 0
}

# shellcheck disable=SC2310
if ! ( dependency_exists 'direnv' \
    && dependency_exists 'yarn'   \
    && dependency_exists 'grep'
); then
    echo "Please install missing dependencies before continuing" >&2
    exit 1
fi

###############################################################################################################################################################

direnv allow .

if ! type code &> /dev/null; then
    if ! code --list-extensions | grep -e '^mkhl.direnv$'; then
        code --install-extension mkhl.direnv
    fi
    if ! code --list-extensions | grep -e '^arcanis.vscode-zipfs$'; then
        code --install-extension arcanis.vscode-zipfs
    fi
fi

yarn
yarn dlx @yarnpkg/sdks vscode
